# Generated by Django 4.2.7 on 2026-03-31 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HerbalPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('scientific_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True)),
                ('medicinal_uses', models.TextField(help_text='List of medicinal uses separated by newlines')),
                ('preparation_steps', models.TextField(help_text='Preparation instructions separated by newlines')),
                ('cultural_relevance', models.TextField(blank=True, help_text='Cultural significance in the Philippines')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Herbal Plant',
                'verbose_name_plural': 'Herbal Plants',
                'ordering': ['name'],
            },
        ),
    ]
