# Generated by Django 4.2.7 on 2026-04-08 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('herbal_plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhotoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='For non-logged users', max_length=100, null=True)),
                ('image', models.ImageField(upload_to='submissions/pending/')),
                ('plant_name', models.CharField(help_text="User's identification", max_length=100)),
                ('ai_prediction', models.CharField(blank=True, help_text='What AI predicted', max_length=100, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('is_correction', models.BooleanField(default=False, help_text='User correcting AI mistake')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('training', 'In Training'), ('trained', 'Trained')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_photo_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(help_text='Is the identification correct?')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='herbal_plants.userphotosubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submission_feedbacks',
            },
        ),
    ]
